version: '2'

services:
  apache:
    image: httpd
    hostname: registry.vibioh.fr
    ports:
    - 5443:443
    links:
    - registry:registry
    volumes:
    - ${REGISTRY_HTTPD_CONF_DIR}:/usr/local/apache2/conf

  registry:
    image: registry:2
    labels:
      traefik.enable: 'false'
    volumes:
    - ${REGISTRY_DIR}:/var/lib/registry
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: 'no'
    read_only: true
