version: '2'

services:
  nginx:
    environment:
    - affinity:container==swarm_manager
  registry:
    environment:
    - affinity:container==swarm_manager

networks:
  default:
    external:
      name: swarm-net
