version: '2'

services:
  nginx:
    image: nginx:1.9
    hostname: registry.vibioh.fr
    labels:
      traefik.enable: 'false'
    ports:
    - 10443:443
    links:
    - registry:registry
    volumes:
    - ${PROXY_CONF_DIR}:/etc/nginx/conf.d
    - ${PROXY_CONF_DIR}/nginx.conf:/etc/nginx/nginx.conf:ro
    logging:
       driver: json-file
       options:
         max-size: '50m'
    restart: 'no'

  registry:
    image: registry:2
    labels:
      traefik.enable: 'false'
    ports:
    - 5000:5000
    volumes:
    - ${REGISTRY_DIR}:/var/lib/registry
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: 'no'

networks:
  default:
    external:
      name: traefik
